pipeline {
  agent any

  environment {
    DOCKER_IMAGE = 'eureka-server'
    DOCKER_TAG = "${BUILD_NUMBER}"
    DOCKER_CREDENTIALS = 'stevelee93' // Jenkins에 등록된 Docker Hub 자격증명 ID

  }
  tools {
    maven 'Maven 3.9.6'
    jdk 'JDK 21'
  }

  stages {
    stage('Checkout') {
      steps{
        checkout scm
      }
    }
    stage('Build'){
      steps{
        dir('eureka-server'){
          powershell 'mvn clean package -DskipTests'
        }
      }
    }
    stage('Unit Test'){
      steps{
        dir('eureka-server'){
          powershell 'mvn test'
        }
      }
      post{
        always{
          junit 'eureka-server/target/surefire-reports/*.xml'
        }
      }
    }
    stage('Build Docker Image'){
      steps{
        dir('eureka-server'){
          script{
            docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
          }
        }
      }
    }
    stage('Push Docker Image'){
      steps{
        dir('eureka-server'){
          script{
            docker.withRegistry('', "${DOCKER_CREDENTIALS}"){
              docker.image("${DOCKER_CREDENTIALS}/${DOCKER_IMAGE}:${DOCKER_TAG}").push()
              docker.image("${DOCKER_CREDENTIALS}/${DOCKER_IMAGE}:${DOCKER_TAG}").push('latest')
            }
          }
        }
      }
    }
    stage('Deploy'){
      steps{
        dir('eureka-server'){
          script{
            powershell 'docker-compose down || true'
            powershell 'docker-compose up -d'
          }
        }
      }
    }
  }
  post{
    always{
      cleanWs()
    }
    success{
      echo 'Pipeline successful.'
    }
    failure{
      echo 'Pipeline failed.'
    }
  }
}