pipeline {
  agent any

  environment {
    DOCKER_IMAGE = 'eureka-server'
    DOCKER_TAG = "${BUILD_NUMBER}"
    DOCKER_CREDENTIALS = 'stevelee93' // Jenkins에 등록된 Docker Hub 자격증명 ID

  }
  tools {
    maven 'Maven 4.0.0'
    jdk 'JDK 21'
  }

  stages {
    stage('Checkout') {
      steps{
        checkout scm
      }
    }
    stage('Build'){
      steps{
        sh 'mvn clean package -DskipTests'
      }
    }
    stage('Unit Test'){
      steps{
        sh 'mvn test'
      }
      post{
        always{
          junit '**/target/surefire-reports/*.xml'
        }
      }
    }
    stage('Build Docker Image'){
      steps{
        script{
          docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
        }
      }
    }
    stage('Push Docker Image'){
      steps{
        script{
          docker.withRegistry('https://registry.hub.docker.com', '${DOCKER_CREDENTIALS}'){
            docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}").push()
            docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}").push('latest')
          }
        }
      }
    }
    stage('Deploy'){
      steps{
        // 실제 배포 스크립트.
        script{
          sh 'docker-compose down || true'
          sh 'docker-compose up -d'
        }
      }
    }
  }
  post{
    always{
      cleanWs()
    }
    success{
      echo 'Pipeline successful.'
    }
    failure{
      echo 'Pipeline failed.'
    }
  }
}